'''Globally relevant variables that are shared between all package scripts.'''
entities = []
appVersion = '0.0.1' # App version.
windowTitle = 'PV Buddy' # App title.
app = None
window = None # Reference to the main window instance.
lightModeOn = True
inspector = None
workspace = None
editors = []
editorOpenIdx = -1;
controlPVs = None
objectivePVs = None
entities = dict() # store each entity along with its ID for sorting and ID assignment reasons.
entityTypes = ['PV', 'GUI'] # can be more than just PVs, anything you might want to save the state of.
cursorTolerance = 15 # tolerance with which to ignore cursor moves due to hand shake.
PVs = []
expandables = [] # expandable widgets displayed in the inspector.
selectedPV = None # PV being displayed in the inspector currently.
editorPopup = None # floating popup inside the editor.
latticePath = ''
elements = None # lattice element references
names = None # lattice element names