0:
  name: MainWindow
  type: MainWindow
1:
  name: Workspace
  type: Workspace
2:
  name: Editor
  positionInSceneCoords:
  - 2035.9333228471019
  - 1579.471724197517
  type: Editor
  zoom: 0.5235927856955934
3:
  linksIn: {}
  linksOut: {}
  name: EditorMenu
  size:
  - 350
  - 250
  type: EditorMenu
4:
  name: Global Lattice
  sceneHeight: 145
  sceneWidth: 1200
  type: Global Lattice
5:
  name: Inspector
  size:
  - 415
  - -1
  type: Inspector
6:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 5.0
      min: -5.0
      name: Slider
      type: SliderComponent
      units: mrad
      value: 0.0
      valueType: float
  linksIn: {}
  linksOut:
    8: decision
  name: BS-PC-VSTR-01:SETI
  position:
  - 1475.0
  - 1469.0
  size:
  - 325
  - 75
  type: PV
7:
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: SliderComponent
      units: mrad
      value: 0
  linksIn: {}
  linksOut:
    8: objective
  name: BS-DI-ICT-03:SIGNAL
  position:
  - 1475.2042752087589
  - 1618.8797305662772
  size:
  - 325
  - 75
  type: PV
8:
  linksIn:
    6: decision
    7: objective
  linksOut: {}
  name: Single Task GP
  position:
  - 2014.533432205917
  - 1406.8692527236926
  size:
  - 600
  - 500
  type: Single Task GP
